kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rbac-viewer
rules:
- apiGroups: ["rbac.authorization.k8s.io"] # "" indicates the core API group
  resources: ["roles", "rolebindings", "clusterroles", "clusterrolebindings"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rbac-viewer
subjects:
- kind: ServiceAccount
  name: rbac-viewer # Name is case sensitive
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: rbac-viewer # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io